backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Configuração de mídia
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

# Configuração de localização
locale: 'pt'

# Configurações do editor
editor:
  preview: true

# Configurações das coleções
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/posts
    label: "Posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string", required: true}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Slug deve conter apenas letras minúsculas, números e hífens'], required: true}
      - {label: "Data de Publicação", name: "date", widget: "datetime", required: true}
      - {label: "Categoria", name: "category", widget: "select", options: ["Direito Civil", "Direito Penal", "Direito Constitucional", "Direito Administrativo", "Direito Trabalhista", "Direito Tributário", "Direito Empresarial", "Direito do Consumidor", "Direito Previdenciário", "Direito Ambiental", "Direito Internacional", "Processo Civil", "Processo Penal", "Jurisprudência", "Legislação", "Doutrina", "Concursos", "OAB", "Outros"], required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false, hint: "Adicione tags separadas por vírgula"}
      - {label: "Imagem Destacada", name: "image", widget: "image", required: false, hint: "Imagem que aparecerá no card do post"}
      - {label: "Descrição", name: "description", widget: "text", required: true, hint: "Breve descrição do post (aparecerá no card e meta description)"}
      - {label: "Autor", name: "author", widget: "string", default: "Manual do Direito", required: true}
      - {label: "Publicado", name: "published", widget: "boolean", default: true}
      - {label: "Destaque", name: "featured", widget: "boolean", default: false, hint: "Posts em destaque aparecem primeiro"}
      - {label: "Conteúdo", name: "body", widget: "markdown", required: true}

  - name: "pages" # Páginas estáticas
    label: "Páginas"
    files:
      - label: "Sobre"
        name: "sobre"
        file: "pages/sobre.md"
        fields:
          - {label: "Título", name: "title", widget: "string", default: "Sobre"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Conteúdo", name: "body", widget: "markdown"}
      - label: "Contato"
        name: "contato"
        file: "pages/contato.md"
        fields:
          - {label: "Título", name: "title", widget: "string", default: "Contato"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Telefone", name: "phone", widget: "string", required: false}
          - {label: "Endereço", name: "address", widget: "text", required: false}
          - {label: "Conteúdo", name: "body", widget: "markdown"}

  - name: "settings" # Configurações do site
    label: "Configurações"
    files:
      - label: "Configurações Gerais"
        name: "general"
        file: "settings/general.yml"
        fields:
          - {label: "Título do Site", name: "site_title", widget: "string", default: "Manual do Direito Online"}
          - {label: "Descrição do Site", name: "site_description", widget: "text", default: "Conteúdo jurídico de qualidade para estudantes e profissionais do direito"}
          - {label: "URL do Site", name: "site_url", widget: "string", default: "https://manualdodireito.online"}
          - {label: "Logo", name: "logo", widget: "image", required: false}
          - {label: "Favicon", name: "favicon", widget: "image", required: false}
          - label: "Redes Sociais"
            name: "social_media"
            widget: "object"
            fields:
              - {label: "Facebook", name: "facebook", widget: "string", required: false}
              - {label: "Twitter", name: "twitter", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "YouTube", name: "youtube", widget: "string", required: false}
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - {label: "Meta Keywords", name: "keywords", widget: "text", required: false}
              - {label: "Google Analytics ID", name: "google_analytics", widget: "string", required: false}
              - {label: "Google Search Console", name: "google_search_console", widget: "string", required: false}

# Configurações de autenticação
site_url: https://manualdodireito.online
display_url: https://manualdodireito.online

# Configurações de busca
search: true

# Configurações de slug
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

